### ISSUE TITLE
Proper Save

### ISSUE THREAD

**Issue by idhamperdameian** [zenangst/MarvinXcode#10]
Proper save not working in Xcode 6.1.1 it not remove trailing whitespace.

**Comment by zenangst** [comment]
I think that feature was scratched, I have enabled it via the Xcode preferences instead and that works just dandy for me.

![screen shot 2015-02-06 at 08 24 42](https://cloud.githubusercontent.com/assets/57446/6075788/d4582a04-add9-11e4-981a-f7cb2e09602c.PNG)

I've updated the README.

**Comment by idhamperdameian** [comment]
Ok, nice. Thank you.
