### ISSUE TITLE
Show how to map to keyboards

### ISSUE THREAD

**Issue by NSElvis** [zenangst/MarvinXcode#13]
I have to show every time I want to tell someone that Proper Save is the thing, and I have to add and find this screenshot every single time. Please consider improving your documentation to include a section that explains how to do this.

![screen shot 2015-03-05 at 1 51 50 pm](https://cloud.githubusercontent.com/assets/1088217/6505088/e2162a36-c33e-11e4-983d-b0e76b54ed25.png)

**Comment by zenangst** [comment]
This is no longer needed!

**Comment by NSElvis** [comment]
OKAY
![897](https://cloud.githubusercontent.com/assets/1088217/6690130/dbd35c3c-ccbe-11e4-8a73-5d709b992f55.gif)
