### ISSUE TITLE
Enable configuration of keyboard shortcuts or disabling of certain ones?

### ISSUE THREAD

**Issue by jawwad** [zenangst/MarvinXcode#15]
Is there a way that keyboard shortcuts can be configured or changed? In the extension Ctrl-A key is mapped to select previous word, however Ctrl-A is a common emacs-style shortcut used to move the cursor to the beginning of the line (and works in most places in OS X). I'd love to just be able to use the extension for Delete, Duplicate and Join line but need to disable it for now as it hinders the text navigation I'm used to with Ctrl-A.

**Comment by zenangst** [comment]
You can reassign keys in System Preferences > Keyboard > Shortcuts. Disabling keys, well that's trickier. 
I guess you could give them a shortcut combination that's impossible to stumble upon; 

For example: `Shift` + `Ctrl` + `Alt` + `Cmd` + `F12`.

Hope that helps :)

**Comment by jawwad** [comment]
@zenangst Aah cool! That works nicely, added an extra Shift in there so assigned it to `Ctrl` + `Shift` + `A` which I probably won't ever hit by accident. Thanks!
