### ISSUE TITLE
This is a good plugin,But I hope I Can Customize my own shortcut key. 

### ISSUE THREAD

**Issue by shenguanjiejie** [zenangst/MarvinXcode#17]

**Comment by zenangst** [comment]
You can totally do that already, just add your own shortcuts in System Preferences > Keyboard > Shortcuts.

![screen shot 2015-04-11 at 11 04 21](https://cloud.githubusercontent.com/assets/57446/7100873/a03d1fb6-e03a-11e4-8f8c-112938aae50f.png)

Related to: https://github.com/zenangst/MarvinXcode/issues/15

**Comment by shenguanjiejie** [comment]
That's great,haha,COOL! Thank you very much...and I think you'd better put this picture in readme.md,Do you think so?

**Comment by shenguanjiejie** [comment]
For the newbie doesn't know how to use this plugin like me...

**Comment by zenangst** [comment]
Very true, thanks @shenguanjiejie, I'll make a task to update the README :+1:

**Comment by zenangst** [comment]
https://github.com/zenangst/MarvinXcode/issues/18

**Comment by zenangst** [comment]
@shenguanjiejie Fixed now

**Comment by shenguanjiejie** [comment]
Well done! Best wishes for you and your plugin.   :)
