### ISSUE TITLE
Default shortcuts

### ISSUE THREAD

**Issue by dev4dev** [zenangst/MarvinXcode#19]
I think it's better to remove some default shortcuts and let the user setup them by himself. For example I use ^A as "go to start of line" and I don't like that it's overwritten with plugins one.

**Comment by zenangst** [comment]
@dev4dev I agree, I'll drop them in the next version

**Comment by dev4dev** [comment]
thanx

**Comment by zenangst** [comment]
@dev4dev fixed in https://github.com/zenangst/MarvinXcode/commit/26770321a76fb7e417d58af4044c6260b129504c
