### ISSUE TITLE
Doesn't work xcode 6.4

### ISSUE THREAD

**Issue by goktugyil** [zenangst/MarvinXcode#24]

**Comment by mkerley** [comment]
I filed a pull request to fix this: https://github.com/zenangst/MarvinXcode/pull/25

**Comment by zenangst** [comment]
Thanks @mkerley :sunglasses:

**Comment by mkerley** [comment]
No problem - happy to help. Thanks for the great plugin!

**Comment by goktugyil** [comment]
How much time does it take to become active in alcatraz?

**Comment by mkerley** [comment]
Should be right away, but you do need to uninstall and reinstall the plugin within Alcatraz, then restart Xcode.

**Comment by goktugyil** [comment]
I uninstalled and reinstalled from Alcatraz a couple of time and still couldn't get this to work

**Comment by zenangst** [comment]
@goktugyil do you see any error messages in the console/logs?

**Comment by goktugyil** [comment]
No, nothing. I am using swift btw and have a few other xcode packages installed

**Comment by zenangst** [comment]
@goktugyil that is super weird, works like a charm here. I'm gonna have another look later today.

**Comment by goktugyil** [comment]
Allright thanks, tell me if there is anyway I could provide more information for you

**Comment by zenangst** [comment]
@goktugyil could you check your plugin directory to see that the Marvin plugin is present?
`~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/`

Also, could you have another look in the logs to see if you get any messages that look like this;

```
15/07/15 18:45:10,118 Xcode[8402]: [MT] PluginLoading: Required plug-in compatibility UUID 7FDF5C7A-131F-4ABB-9EDC-8C5F8F0B8A90 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Marvin.xcplugin' not present in DVTPlugInCompatibilityUUIDs
```

**Comment by kevinwo** [comment]
I also am unable to get Marvin to work in Xcode 6.4. Installed via Alcatraz. Seeing the plugin installed in ~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/.

**Comment by zenangst** [comment]
@kevinwo any errors in the console?
