### ISSUE TITLE
Improve README on how to use

### ISSUE THREAD

**Issue by onmyway133** [zenangst/MarvinXcode#35]
I think we should add these to the README for an easy usage

- Accessible via Edit -> Marvin
- Keyboard shortcuts (in System Preferences) names should match Marvin commands
- Automatically adds a LF at the end of document

**Comment by zenangst** [comment]
@onmyway133 great idea, you know what would be even greater? A pull request :sunglasses: 

![giphy-22](https://cloud.githubusercontent.com/assets/57446/11532942/5c7542e6-9907-11e5-976a-46d880f4b756.gif)
