### ISSUE TITLE
Disabling "Remove Whitespace" has no effect

### ISSUE THREAD

**Issue by noahemmet** [zenangst/MarvinXcode#39]

**Comment by zenangst** [comment]
Hey @noahemmet, I've been noticing this as well. I'll do some investigation and get back to you on this. I though this was fixed by this thing; https://github.com/zenangst/MarvinXcode/pull/33/files

I'll take another look :sunglasses:

**Comment by noahemmet** [comment]
Ok thanks! I was going to write up an actual explanation but I hit the return key too early!

**Comment by zenangst** [comment]
@noahemmet could you take the new version for a spin to see if this thing is fixed now? :sunglasses:

**Comment by noahemmet** [comment]
Fixed it for me! Thanks again!

**Comment by zenangst** [comment]
@noahemmet :beers:
