### ISSUE TITLE
Does not work with Xcode 8 / Swift 3

### ISSUE THREAD

**Issue by neave** [zenangst/MarvinXcode#50]
Running this projects in Xcode 8 requires migrating to Swift 2.3 or 3.

**Comment by zenangst** [comment]
Xcode 8 does not support plugins like Xcode 7 did without unsigning the binary. Hence me re-writing Marvin as an Xcode extension that works with Xcode 8.

You can find the current implementation here -> https://github.com/zenangst/Marvin-Xcode-Extension

**Comment by neave** [comment]
Brilliant, thanks @zenangst. Would be great if you could add a link to the extension version in the README.

**Comment by zenangst** [comment]
@neave great idea, I'll updated it 😁
