### ISSUE TITLE
Wiping a playground and pressing "Proper save" crashes Xcode

### ISSUE THREAD

**Issue by NSElvis** [zenangst/MarvinXcode#9]

**Comment by zenangst** [comment]
I think that was just Xcode being an asshole, unable to reproduce this.

**Comment by zenangst** [comment]
My bad!

**Comment by zenangst** [comment]
Fixed in https://github.com/zenangst/MarvinXcode/pull/11

**Comment by NSElvis** [comment]
:star:  :hamburger: :star:
